id: sync_result
namespace: scheduler

triggers:
  - id: hourly
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"

tasks:
  - id: call_sync_result
    type: io.kestra.plugin.core.http.Request
    uri: "http://automation-v2-api:8000/api/sync-result"
    method: POST
    contentType: application/json
    body: |
      {"type": "both", "client_id": "{{ secret('SYNC_RESULT_CLIENT_ID') }}"}
