# Generated by Django 6.0.7 on 2026-09-30 22:23

import automation_v2.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('client_id', models.CharField(default=automation_v2.models.new_client_id, max_length=40, unique=True)),
                ('secret', models.CharField(default=automation_v2.models.new_webhook_secret, max_length=100)),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhooks',
                'ordering': ['-id'],
            },
        ),
    ]
